import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { collectCategories, filterBlueprints, matchesBlueprint, paginate, scmdbFabUrl, splitOwners } from '../public/js/inventory-core.js';

const data=[{tag:'Aegis-01',product_name:'Shield Generator',category:'Armor',is_new:true,is_week:true,owner_name:'Alice\nBob'},{tag:'Laser-02',product_name:'Laser Cannon',category:'Weapon',is_new:false,is_week:true,owner_name:'Cara'}];
test('matches product name and tag case-insensitively',()=>{assert.equal(matchesBlueprint(data[0],'shield'),true);assert.equal(matchesBlueprint(data[0],'aegis-01'),true);assert.equal(matchesBlueprint(data[0],'laser'),false)});
test('filters combined search, category and backend recent flags',()=>{assert.deepEqual(filterBlueprints(data,{query:'shield',category:'Armor'}).map(bp=>bp.tag),['Aegis-01']);assert.deepEqual(filterBlueprints(data,{category:'__new__'}).map(bp=>bp.tag),['Aegis-01']);assert.deepEqual(filterBlueprints(data,{category:'__week__'}).map(bp=>bp.tag),['Aegis-01','Laser-02']);assert.deepEqual(filterBlueprints(data,{category:'Weapon'}).map(bp=>bp.tag),['Laser-02'])});
test('clearing the shared category filter restores all blueprints',()=>assert.deepEqual(filterBlueprints(data,{query:'',category:''}).map(bp=>bp.tag),['Aegis-01','Laser-02']));
test('collects dynamic categories and owners',()=>{assert.deepEqual(collectCategories(data),['Armor','Weapon']);assert.deepEqual(splitOwners('Alice\nBob'),['Alice','Bob'])});
test('profile links remain optional in blueprint ownership data',()=>{const owners=[{name:'Alice',profile_path:'/profile/00000000-0000-0000-0000-000000000001'},{name:'Bob',profile_path:null}];assert.equal(owners[0].profile_path.startsWith('/profile/'),true);assert.equal(owners[1].profile_path,null)});
test('encodes SCMDB fabrication tags',()=>assert.match(scmdbFabUrl('Aegis 01'),/Aegis%2001/));
test('paginates empty and single-page collections safely',()=>{for(const size of [0,1,9]){const page=paginate(Array.from({length:size},(_,index)=>index),1,9);assert.equal(page.totalPages,1);assert.equal(page.page,1);assert.equal(page.items.length,size)}assert.deepEqual(paginate([],4,9),{items:[],page:1,pageSize:9,totalItems:0,totalPages:1,startIndex:0,endIndex:0})});
test('paginates multi-page collections and clamps requested pages',()=>{for(const [size,pages,lastSize] of [[10,2,1],[18,2,9],[19,3,1]]){const page=paginate(Array.from({length:size},(_,index)=>index),pages,9);assert.equal(page.totalPages,pages);assert.equal(page.items.length,lastSize);assert.equal(page.page,pages)}const clamped=paginate(Array.from({length:10},(_,index)=>index),5,9);assert.equal(clamped.page,2);assert.deepEqual(clamped.items,[9])});
test('applies pagination after shared filtering',()=>{const blueprints=Array.from({length:20},(_,index)=>({tag:`BP-${index}`,product_name:index<11?'Shield':'Laser',category:index<11?'Shield':'Weapon'}));const filtered=filterBlueprints(blueprints,{query:'shield'}),first=paginate(filtered,1,9),last=paginate(filtered,2,9);assert.equal(filtered.length,11);assert.equal(first.totalPages,2);assert.equal(first.items.length,9);assert.equal(last.items.length,2)});
test('Mobiglass Inventory uses the unfiltered inventory logo',async()=>{const [server,mobiglass]=await Promise.all([readFile(new URL('../src/server.js',import.meta.url),'utf8'),readFile(new URL('../public/js/inventory-mobiglass.js',import.meta.url),'utf8')]);assert.match(mobiglass,/<img class="mi-logo" src="\/assets\/apps\/inventory\.png" alt="Blueprint Inventory">/);assert.match(mobiglass,/\.mi-logo\{[^}]*object-fit:contain/);assert.doesNotMatch(mobiglass,/\.mi-logo\{[^}]*\b(?:filter|opacity|mix-blend-mode)\s*:/);assert.match(mobiglass,/const unavailableImage=\{image:'\/assets\/apps\/blueprint-image-unavailable\.png'\}/);assert.match(mobiglass,/const mediaFor=bp=>bp\.image_url\?\{image:bp\.image_url,source:bp\.source_url\}:\{\.\.\.unavailableImage,source:bp\.source_url\|\|null\}/);assert.match(mobiglass,/const openProfile=async/);assert.match(mobiglass,/bindProfileClose/);assert.match(mobiglass,/\.mi \.mi-owner-link/);assert.match(mobiglass,/profile\.discord_name,'Not provided'/);assert.match(mobiglass,/mi-profile-dialog/);assert.match(server,/publicProfileApiMatch/);assert.match(server,/"\/assets\/apps\/inventory\.png"/);assert.match(server,/"\/assets\/apps\/blueprint-image-unavailable\.png"/)});
