import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
const source = await readFile(new URL('../public/js/missions-mobiglass.js', import.meta.url), 'utf8');
test('mission overview uses group context and exactly one selected-group list request', () => { assert.match(source, /fetch\('\/api\/groups'\)/); assert.match(source, /missionApi \+ '\?group_id=' \+ encodeURIComponent\(groupId\)/); assert.doesNotMatch(source, /Promise\.all\(state\.groups/); assert.doesNotMatch(source, /missions\/\$\{|\/tasks|\/contributions/); });
test('mission overview preserves server order and filters locally by status and title', () => { assert.doesNotMatch(source, /\.sort\(/); assert.match(source, /\['open', 'in_progress'\]\.includes\(mission\.status\)/); assert.match(source, /state\.search\.trim\(\)\.toLowerCase\(\)/); assert.match(source, /String\(mission\.title \?\? ''\)\.toLowerCase\(\)\.includes\(search\)/); });
test('mission search keeps its toolbar DOM and rerenders only the results region', () => { assert.match(source, /data-missions-results/); assert.match(source, /const renderMissionResults/); const handler = source.match(/data-missions-search\]'\)\?\.addEventListener\('input', event => \{[^}]+\}/)?.[0] || ''; assert.match(handler, /state\.search = event\.target\.value/); assert.match(handler, /renderMissionResults\(\)/); assert.doesNotMatch(handler, /\brender\(\)|fetch\(|innerHTML/); });
test('mission cards render only list response summary fields safely', () => { for (const field of ['progress_percent', 'active_task_count', 'created_at', 'updated_at', 'completed_at']) assert.ok(source.includes(`mission.${field}`)); assert.match(source, /const esc = value/); assert.match(source, /clampPercent/); assert.doesNotMatch(source, /assigned_to|RESPONSIBILITY/); });
test('overview exposes required states, refresh, and stale response protection', () => { for (const label of ['LOADING GROUP CONTEXT...', 'LOADING MISSIONS...', 'NO GROUPS AVAILABLE', 'NO MISSIONS', 'NO MATCHING MISSIONS', 'MISSION DATA UNAVAILABLE', 'GROUP CONTEXT UNAVAILABLE', 'GROUP ACCESS CHANGED']) assert.ok(source.includes(label)); assert.match(source, /export async function refresh\(\)/); assert.doesNotMatch(source, /location\.reload/); assert.match(source, /requestGeneration/); assert.match(source, /isLive\(generation, groupId\)/); assert.match(source, /response\.status === 401/); assert.match(source, /response\.status === 403/); });
