using System.Drawing;
using System.Text.Json;
using System.IO;
using System.Threading;
using System.Text.RegularExpressions;
using ThreadingTimer=System.Threading.Timer;
namespace VerseLink.Companion;
public sealed class AutomaticForm:Form{
 readonly RoiCanvas image=new(){Dock=DockStyle.Fill,BorderStyle=BorderStyle.FixedSingle};readonly TextBox output=new(){Dock=DockStyle.Fill,Multiline=true,ScrollBars=ScrollBars.Both,ReadOnly=true,Font=new Font("Consolas",10)};Bitmap? source;string? sourcePath;OcrResult? lastOcr;RefineryCompletedParseResult? lastResult;FileSystemWatcher? watcher;ThreadingTimer? watchTimer;readonly TextBox watchPath=new(){Width=430,Text=@"O:\Roberts Space Industries\StarCitizen\LIVE\screenshots"};readonly Button watchButton=new(){Text="Start Folder Watch"};readonly CheckBox copyScreenshot=new(){Text="Copy analyzed screenshot",Checked=true,AutoSize=true};
 public AutomaticForm(){Text="VerseLink Companion - Phase 0.6";Width=1200;Height=800;var open=new Button{Text="Open Screenshot"};open.Click+=(_,_)=>Open();var analyze=new Button{Text="Analyze Automatically"};analyze.Click+=async(_,_)=>await Analyze();var export=new Button{Text="Export JSON"};export.Click+=(_,_)=>Export();var bar=new FlowLayoutPanel{Dock=DockStyle.Top,Height=42};bar.Controls.AddRange([open,analyze,export]);var split=new SplitContainer{Dock=DockStyle.Fill};split.Panel1.Controls.Add(image);split.Panel2.Controls.Add(output);Controls.Add(split);Controls.Add(bar);}
 protected override void OnLoad(EventArgs e){base.OnLoad(e);var bar=Controls.OfType<FlowLayoutPanel>().FirstOrDefault();if(bar==null)return;bar.Height=76;bar.Controls.Add(new Label{Text="Screenshot folder:",AutoSize=true,Padding=new Padding(0,7,0,0)});bar.Controls.Add(watchPath);watchButton.Click+=(_,_)=>ToggleWatch();bar.Controls.Add(watchButton);bar.Controls.Add(copyScreenshot);}
 void Open(){using var d=new OpenFileDialog{Filter="Images|*.png;*.jpg;*.jpeg"};if(d.ShowDialog()!=DialogResult.OK)return;LoadImage(d.FileName);output.Text="Screenshot loaded. Click Analyze Automatically.";}
 void LoadImage(string path){using var stream=new FileStream(path,FileMode.Open,FileAccess.Read,FileShare.ReadWrite);using var loaded=new Bitmap(stream);source?.Dispose();source=new Bitmap(loaded);sourcePath=path;image.Image=source;}
 void ToggleWatch(){if(watcher!=null){watcher.Dispose();watcher=null;watchTimer?.Dispose();watchTimer=null;watchButton.Text="Start Folder Watch";output.Text="Folder watch stopped.";return;}var folder=watchPath.Text.Trim();if(!Directory.Exists(folder)){output.Text=$"WATCH_FOLDER_NOT_FOUND\r\n{folder}";return;}watcher=new FileSystemWatcher(folder){Filter="*.*",NotifyFilter=NotifyFilters.FileName|NotifyFilters.CreationTime,IncludeSubdirectories=false,EnableRaisingEvents=true};watcher.Created+=(_,e)=>QueueFile(e.FullPath);watcher.Renamed+=(_,e)=>QueueFile(e.FullPath);watchButton.Text="Stop Folder Watch";output.Text=$"Folder watch active:\r\n{folder}\r\n\r\nWaiting for a new screenshot...";}
 void QueueFile(string path){var ext=Path.GetExtension(path);if(!new[]{".png",".jpg",".jpeg"}.Contains(ext,StringComparer.OrdinalIgnoreCase))return;watchTimer?.Dispose();watchTimer=new ThreadingTimer(_=>{try{BeginInvoke(new Action(async()=>{try{LoadImage(path);output.Text=$"Auto-processing: {Path.GetFileName(path)}\r\n";await Analyze();}catch(Exception ex){output.Text=$"AUTO_WATCH_FAILED\r\n{ex.Message}";}}));}catch{ }},null,900,Timeout.Infinite);}
 async Task Analyze(){if(source==null){output.Text="IMAGE_LOAD_FAILED";return;}var path=Path.Combine(Path.GetTempPath(),"verselink-companion-auto.png");try{source.Save(path,System.Drawing.Imaging.ImageFormat.Png);lastOcr=await new WindowsOcrEngine().RecognizeDetailedAsync(path);var detected=AutomaticRegionDetector.Detect(lastOcr);if(detected.Location==null||detected.WorkOrder==null){output.Text="AUTO_REGION_NOT_CONFIDENT";return;}var locationWords=lastOcr.Words.Where(w=>Inside(w,detected.Location.Value,lastOcr)).ToArray();var workWords=lastOcr.Words.Where(w=>Inside(w,detected.WorkOrder.Value,lastOcr)).ToArray();var location=string.Join(" ",locationWords.Select(w=>w.Text));var work=new OcrResult(string.Join(Environment.NewLine,workWords.Select(w=>w.Text)),[],workWords,lastOcr.ImageWidth,lastOcr.ImageHeight,lastOcr.Duration);lastResult=RefinerySpatialParser.Parse(work,location) with {PlayerName=FindPlayerName(lastOcr)};var logFolder=Path.Combine(AppContext.BaseDirectory,"logs");Directory.CreateDirectory(logFolder);var baseName=Path.GetFileNameWithoutExtension(sourcePath??"analysis");var autoJson=Path.Combine(logFolder,baseName+".json");File.WriteAllText(autoJson,JsonSerializer.Serialize(lastResult,new JsonSerializerOptions{WriteIndented=true}));var copiedImage=copyScreenshot.Checked&&sourcePath!=null?Path.Combine(logFolder,Path.GetFileName(sourcePath)):null;if(copiedImage!=null&&!string.Equals(Path.GetFullPath(sourcePath!),Path.GetFullPath(copiedImage),StringComparison.OrdinalIgnoreCase))File.Copy(sourcePath!,copiedImage,true);var player=lastResult.PlayerName??"UNKNOWN";output.Text=$"Player: {player}\r\nLocation: {lastResult.Location}\r\nScreen: {lastResult.ScreenType}\r\nAuto confidence: location {detected.LocationConfidence:P0}, work order {detected.WorkOrderConfidence:P0}\r\n\r\n"+string.Join("\r\n",lastResult.Rows.Select(r=>$"{r.NormalizedMaterialName,-12} {r.Quality,7} {r.YieldCscu,10} {r.Confidence:P0} {string.Join(",",r.Warnings)}"))+ $"\r\n\r\nWarnings: {string.Join(", ",lastResult.Warnings)}\r\n\r\nJSON export: {autoJson}\r\nScreenshot copy: {(copiedImage??"disabled")}\r\n\r\nRAW OCR:\r\n{lastOcr.RawText}";}catch(Exception ex){output.Text=$"OCR_FAILED\r\n{ex.Message}";}finally{if(File.Exists(path))File.Delete(path);}}
 static string? FindPlayerName(OcrResult o){var match=Regex.Match(o.RawText, @"\bUSER\s+([A-Z][A-Z0-9_-]{2,})\b", RegexOptions.IgnoreCase);if(match.Success&&!Regex.IsMatch(match.Groups[1].Value,@"^(YIELD|FUNDS|REFINEMENT|CENTER)$",RegexOptions.IgnoreCase))return match.Groups[1].Value;var user=o.Words.FirstOrDefault(w=>w.Text.Trim('/',' ').Equals("USER",StringComparison.OrdinalIgnoreCase));if(user==null)return null;return o.Words.Where(w=>w.X>user.X+user.Width&&Math.Abs(w.Y-user.Y)<=Math.Max(user.Height*2,24)&&w.Text.Any(char.IsLetter)&&!w.Text.Contains("//")).OrderBy(w=>w.X).Select(w=>w.Text.Trim()).FirstOrDefault();}
 static bool Inside(OcrWord w,RegionOfInterest roi,OcrResult o){var r=roi.ToPixels(o.ImageWidth,o.ImageHeight);return RectangleF.Intersect(new RectangleF((float)w.X,(float)w.Y,(float)w.Width,(float)w.Height),r).Width>0;}
 void Export(){if(lastResult==null)return;using var d=new SaveFileDialog{Filter="JSON|*.json",FileName="refinery-auto-result.json"};if(d.ShowDialog()==DialogResult.OK)File.WriteAllText(d.FileName,JsonSerializer.Serialize(lastResult,new JsonSerializerOptions{WriteIndented=true}));}
 protected override void Dispose(bool disposing){if(disposing){watcher?.Dispose();watchTimer?.Dispose();source?.Dispose();}base.Dispose(disposing);}
}
