using System.Text.RegularExpressions;
namespace VerseLink.Companion;
public enum LocationMatchType{EXACT,UNIQUE_ALIAS,AMBIGUOUS,UNKNOWN}
public sealed record RefineryLocation(string Id,string System,string Name,IReadOnlyList<string> Aliases);
public sealed record RefineryLocationMatch(string RawLocation,RefineryLocation? Location,LocationMatchType MatchType){public string? LocationId=>Location?.Id;public string? System=>Location?.System;public string? Name=>Location?.Name;}
public static class RefineryLocationCatalog{
 static string N(string s)=>Regex.Replace(s.ToUpperInvariant().Trim().Replace('–','-'),@"\s+|-","");
 static readonly IReadOnlyList<RefineryLocation> All=new List<RefineryLocation>{
  new("stanton-arc-l1","Stanton","ARC-L1 Wide Forest Station",["ARC-L1","WIDE FOREST","WIDE FOREST STATION"]),new("stanton-arc-l2","Stanton","ARC-L2 Lively Pathway Station",["ARC-L2","LIVELY PATHWAY","LIVELY PATHWAY STATION"]),new("stanton-arc-l4","Stanton","ARC-L4 Faint Glen Station",["ARC-L4","FAINT GLEN","FAINT GLEN STATION"]),new("stanton-cru-l1","Stanton","CRU-L1 Ambitious Dream Station",["CRU-L1","AMBITIOUS DREAM","AMBITIOUS DREAM STATION"]),new("stanton-hur-l1","Stanton","HUR-L1 Green Glade Station",["HUR-L1","GREEN GLADE","GREEN GLADE STATION"]),new("stanton-hur-l2","Stanton","HUR-L2 Faithful Dream Station",["HUR-L2","FAITHFUL DREAM","FAITHFUL DREAM STATION"]),new("stanton-mic-l1","Stanton","MIC-L1 Shallow Frontier Station",["MIC-L1","SHALLOW FRONTIER","SHALLOW FRONTIER STATION"]),new("stanton-mic-l2","Stanton","MIC-L2 Long Forest Station",["MIC-L2","LONG FOREST","LONG FOREST STATION"]),new("stanton-mic-l5","Stanton","MIC-L5 Modern Icarus Station",["MIC-L5","MODERN ICARUS","MODERN ICARUS STATION"]),new("stanton-nyx-gateway","Stanton","Nyx Gateway (Stanton)",["NYX GATEWAY"]),new("stanton-pyro-gateway","Stanton","Pyro Gateway (Stanton)",["PYRO GATEWAY"]),new("stanton-terra-gateway","Stanton","Terra Gateway (Stanton)",["TERRA GATEWAY"]),
  new("pyro-checkmate","Pyro","Checkmate Station",["CHECKMATE","CHECKMATE STATION"]),new("pyro-orbituary","Pyro","Orbituary",["ORBITUARY"]),new("pyro-ruin","Pyro","Ruin Station",["RUIN","RUIN STATION"]),new("pyro-stanton-gateway","Pyro","Stanton Gateway (Pyro)",["STANTON GATEWAY"]),new("pyro-nyx-gateway","Pyro","Nyx Gateway (Pyro)",["NYX GATEWAY"]),
  new("nyx-levski","Nyx","Levski",["LEVSKI"]),new("nyx-pyro-gateway","Nyx","Pyro Gateway (Nyx)",["PYRO GATEWAY"]),new("nyx-stanton-gateway","Nyx","Stanton Gateway (Nyx)",["STANTON GATEWAY"])};
 public static RefineryLocationMatch Match(string raw,string? systemHint=null){var key=N(raw);var hits=All.Where(x=>x.Aliases.Any(a=>key==N(a)||key.Contains(N(a),StringComparison.Ordinal))).OrderByDescending(x=>x.Aliases.Max(a=>N(a).Length)).ToList();if(!string.IsNullOrWhiteSpace(systemHint))hits=hits.Where(x=>string.Equals(x.System,systemHint.Trim(),StringComparison.OrdinalIgnoreCase)).ToList();var distinct=hits.GroupBy(x=>x.Id).Select(x=>x.First()).ToList();if(distinct.Count==1){var exact=key==N(distinct[0].Name);return new(raw,distinct[0],exact?LocationMatchType.EXACT:LocationMatchType.UNIQUE_ALIAS);}return new(raw,null,distinct.Count>1?LocationMatchType.AMBIGUOUS:LocationMatchType.UNKNOWN);}
}
