using System.Text.Json;
using System.Drawing;
using System.Diagnostics;
using System.Text.RegularExpressions;
using Windows.Graphics.Imaging;
using Windows.Media.Ocr;
using Windows.Storage;
using Windows.Storage.Streams;
namespace VerseLink.Companion;
public sealed record MiningMaterialRow(string RawMaterialName,string NormalizedMaterialName,int? Quality,int? Quantity,double Confidence,IReadOnlyList<string> Warnings);
public sealed record MiningOcrResult(string RawText,IReadOnlyList<MiningMaterialRow> Rows,IReadOnlyList<string> Warnings,IReadOnlyList<string> Errors);
public static class MaterialCatalog{
 static readonly string[] Names=["Tungsten","Borase","Lindinium","Stileron","Taranite","Bexalite","Laranite","Iron","Copper","Gold","Titanium"];
 public static string Normalize(string value){var x=Regex.Replace(value.Trim(),@"\s*(\(?\s*(ORE|RAW)\s*\)?)\s*$","",RegexOptions.IgnoreCase);x=Regex.Replace(x,@"[^A-Za-z0-9 ]","");x=Regex.Replace(x,@"\s+"," ").Trim();return Names.FirstOrDefault(n=>n.Equals(x,StringComparison.OrdinalIgnoreCase))??x;}
 public static(string Name,double Score) Match(string raw){var n=Normalize(raw);var e=Names.FirstOrDefault(x=>x.Equals(n,StringComparison.OrdinalIgnoreCase));if(e!=null)return(e,1);var p=Names.Where(x=>n.Contains(x,StringComparison.OrdinalIgnoreCase)||x.Contains(n,StringComparison.OrdinalIgnoreCase)).ToList();return p.Count==1?(p[0],.75):("UNKNOWN MATERIAL",0);}
}
public static class NumericParser{
 public static(int? Value,string? Warning) Parse(string text){var c=text.Trim();var x=Regex.Replace(c,"[IO]","1",RegexOptions.IgnoreCase);x=Regex.Replace(x,"[OS]","5",RegexOptions.IgnoreCase);x=Regex.Replace(x,"B","8",RegexOptions.IgnoreCase);return int.TryParse(x,out var v)?(v,x!=c?"OCR_NUMERIC_CORRECTION":null):(null,null);}
}
public static class MiningParser{
 public static MiningOcrResult Parse(string raw){var rows=new List<MiningMaterialRow>();var allWarnings=new List<string>();string? material=null;int? quality=null,quantity=null;var ws=new List<string>();
 void Flush(){if(material==null)return;var m=MaterialCatalog.Match(material);if(m.Name=="UNKNOWN MATERIAL")ws.Add("UNKNOWN MATERIAL");if(quality is null or <0 or >1000)ws.Add("INVALID_QUALITY");if(quantity is null or <0)ws.Add("INVALID_QUANTITY");allWarnings.AddRange(ws);var score=Math.Min(1,Math.Max(0,m.Score+(quality is >= 0 and <= 1000 ? .1 : 0)+(quantity is >= 0 ? .1 : 0)-ws.Count(x=>x=="OCR_NUMERIC_CORRECTION")*.1));rows.Add(new(material,m.Name,quality,quantity,Math.Round(score,2),ws.ToArray()));material=null;quality=quantity=null;ws.Clear();}
 foreach(var line in raw.Split(['\r','\n'],StringSplitOptions.RemoveEmptyEntries|StringSplitOptions.TrimEntries)){if(Regex.IsMatch(line,@"^(QUALITY|QTY|QUANTITY)\b",RegexOptions.IgnoreCase)){var n=NumericParser.Parse(Regex.Replace(line,@"^(QUALITY|QTY|QUANTITY)\s*","",RegexOptions.IgnoreCase));if(Regex.IsMatch(line,@"^QTY|^QUANTITY",RegexOptions.IgnoreCase))quantity=n.Value;else quality=n.Value;if(n.Warning!=null)ws.Add(n.Warning);}else if(material!=null&&(line.Contains("ORE",StringComparison.OrdinalIgnoreCase)||line.Contains("RAW",StringComparison.OrdinalIgnoreCase))){Flush();material=line;}else if(material==null)material=line;}Flush();return new(raw,rows,allWarnings.Distinct().ToArray(),[]);}
}
public interface IOcrEngine{Task<string> RecognizeAsync(string imagePath,CancellationToken cancellationToken=default);}
public sealed class WindowsOcrEngine:IOcrEngine{
 public async Task<string> RecognizeAsync(string imagePath,CancellationToken cancellationToken=default)=>(await RecognizeDetailedAsync(imagePath,cancellationToken)).RawText;
 public async Task<OcrResult> RecognizeDetailedAsync(string imagePath,CancellationToken cancellationToken=default){var sw=Stopwatch.StartNew();var file=await StorageFile.GetFileFromPathAsync(imagePath);using IRandomAccessStream stream=await file.OpenAsync(FileAccessMode.Read);var decoder=await BitmapDecoder.CreateAsync(stream);using var bitmap=await decoder.GetSoftwareBitmapAsync();var engine=OcrEngine.TryCreateFromUserProfileLanguages()??throw new InvalidOperationException("OCR_FAILED: no Windows OCR language is installed.");var result=await engine.RecognizeAsync(bitmap);var words=result.Lines.SelectMany(l=>l.Words.Select(w=>new OcrWord(w.Text,w.BoundingRect.X,w.BoundingRect.Y,w.BoundingRect.Width,w.BoundingRect.Height))).ToArray();var lines=result.Lines.Select(l=>new OcrLine(l.Text,words.Where(w=>l.Words.Any(x=>x.Text==w.Text)).ToArray())).ToArray();return new OcrResult(result.Text,lines.Select(l=>l.Text).ToArray(),words,(int)bitmap.PixelWidth,(int)bitmap.PixelHeight,sw.Elapsed);}}
public sealed class MainForm:Form{
 readonly TextBox raw=new(){Multiline=true,ScrollBars=ScrollBars.Both,Dock=DockStyle.Fill,Font=new Font("Consolas",10)};readonly TextBox parsed=new(){Multiline=true,ScrollBars=ScrollBars.Both,Dock=DockStyle.Fill,ReadOnly=true,Font=new Font("Consolas",10)};readonly RoiCanvas preview=new(){Dock=DockStyle.Fill,BorderStyle=BorderStyle.FixedSingle}; Bitmap? source; RegionOfInterest? locationRoi,workRoi; Point dragStart; RegionType? selecting; Rectangle dragRect; bool dragging; MiningOcrResult? result;
 public MainForm(){Text="VerseLink Companion - Mining OCR Prototype";Width=1200;Height=800;var open=new Button{Text="Open Screenshot"};open.Click+=(_,_)=>OpenImage();var capture=new Button{Text="Capture Full Screen"};capture.Click+=async(_,_)=>await CaptureScreen();var loc=new Button{Text="Define Location Region"};loc.Click+=(_,_)=>selecting=RegionType.Location;var wo=new Button{Text="Define Work Order Region"};wo.Click+=(_,_)=>selecting=RegionType.WorkOrder;var analyze=new Button{Text="Analyze"};analyze.Click+=async(_,_)=>await Analyze();var export=new Button{Text="Export Result"};export.Click+=(_,_)=>Export();var bar=new FlowLayoutPanel{Dock=DockStyle.Top,Height=42};bar.Controls.AddRange([open,capture,loc,wo,analyze,export]);preview.MouseDown+=PreviewMouseDown;preview.MouseMove+=PreviewMouseMove;preview.MouseUp+=PreviewMouseUp;preview.Paint+=PreviewPaint;var right=new SplitContainer{Dock=DockStyle.Fill,Orientation=Orientation.Horizontal};right.Panel1.Controls.Add(raw);right.Panel2.Controls.Add(parsed);var split=new SplitContainer{Dock=DockStyle.Fill};split.Panel1.Controls.Add(preview);split.Panel2.Controls.Add(right);Controls.Add(split);Controls.Add(bar);}
 void OpenImage(){using var d=new OpenFileDialog{Filter="Images|*.png;*.jpg;*.jpeg"};if(d.ShowDialog()!=DialogResult.OK)return;source?.Dispose();source=new Bitmap(d.FileName);preview.Image=source;locationRoi=workRoi=null;raw.Text="Screenshot loaded. Define both ROIs, then Analyze.";}
 async Task CaptureScreen(){var path=Path.Combine(Path.GetTempPath(),"verselink-companion-capture.png");using var b=new Bitmap(Screen.PrimaryScreen!.Bounds.Width,Screen.PrimaryScreen.Bounds.Height);using(var g=Graphics.FromImage(b))g.CopyFromScreen(Screen.PrimaryScreen.Bounds.Location,Point.Empty,b.Size);b.Save(path,System.Drawing.Imaging.ImageFormat.Png);await Scan(path);}
 void PreviewMouseDown(object? s,MouseEventArgs e){if(e.Button!=MouseButtons.Left||source==null||selecting==null)return;dragStart=e.Location;dragRect=Rectangle.Empty;dragging=true;preview.Capture=true;preview.DragOverlay=Rectangle.Empty;preview.Invalidate();}
 void PreviewMouseMove(object? s,MouseEventArgs e){if(!dragging||selecting==null)return;var x=Math.Clamp(e.X,0,preview.ClientSize.Width-1);var y=Math.Clamp(e.Y,0,preview.ClientSize.Height-1);dragRect=new Rectangle(Math.Min(dragStart.X,x),Math.Min(dragStart.Y,y),Math.Abs(x-dragStart.X),Math.Abs(y-dragStart.Y));preview.DragOverlay=dragRect;preview.DragOverlayColor=selecting==RegionType.Location?Color.Lime:Color.Orange;preview.Invalidate();}
 void PreviewMouseUp(object? s,MouseEventArgs e){if(e.Button!=MouseButtons.Left||source==null||selecting==null||!dragging)return;var mode=selecting.Value;var selected=dragRect;dragging=false;preview.Capture=false;preview.DragOverlay=Rectangle.Empty;dragRect=Rectangle.Empty;selecting=null;if(selected.Width<4||selected.Height<4){preview.Invalidate();return;}var imageRect=GetImageRect();var clipped=Rectangle.Intersect(selected,imageRect);if(clipped.Width<4||clipped.Height<4){preview.Invalidate();return;}var r=new Rectangle(clipped.X-imageRect.X,clipped.Y-imageRect.Y,clipped.Width,clipped.Height);var roi=RegionOfInterest.FromPixels(mode,r,source.Width,source.Height);if(mode==RegionType.Location){locationRoi=roi;preview.SavedLocationOverlay=clipped;}else{workRoi=roi;preview.SavedWorkOrderOverlay=clipped;}preview.Invalidate();}
 Rectangle GetImageRect()=>preview.DisplayedImageRectangle;
 void PreviewPaint(object? sender,PaintEventArgs e){var imageRect=GetImageRect();if(source==null)return;foreach(var pair in new[]{(locationRoi,Color.Lime),(workRoi,Color.Orange)})if(pair.Item1 is RegionOfInterest roi){var original=roi.ToPixels(source.Width,source.Height);var r=new Rectangle(imageRect.X+(int)(original.X*(double)imageRect.Width/source.Width),imageRect.Y+(int)(original.Y*(double)imageRect.Height/source.Height),(int)(original.Width*(double)imageRect.Width/source.Width),(int)(original.Height*(double)imageRect.Height/source.Height));using var pen=new Pen(pair.Item2,3);e.Graphics.DrawRectangle(pen,r);}if(selecting!=null&&dragRect.Width>0&&dragRect.Height>0){using var pen=new Pen(selecting==RegionType.Location?Color.Lime:Color.Orange,2){DashStyle=System.Drawing.Drawing2D.DashStyle.Dash};e.Graphics.DrawRectangle(pen,dragRect);}}
 protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);}
 async Task Analyze(){if(source==null){parsed.Text="IMAGE_LOAD_FAILED";return;}if(locationRoi==null){parsed.Text="NO_LOCATION_ROI";return;}if(workRoi==null){parsed.Text="NO_WORK_ORDER_ROI";return;}var engine=new WindowsOcrEngine();var fullPath=Path.Combine(Path.GetTempPath(),"verselink-companion-analysis.png");try{source.Save(fullPath,System.Drawing.Imaging.ImageFormat.Png);var all=await engine.RecognizeDetailedAsync(fullPath);var locationWords=FilterWords(all,locationRoi.Value);var workWords=FilterWords(all,workRoi.Value);var locationText=string.Join(" ",locationWords.Select(w=>w.Text));var workText=string.Join(Environment.NewLine,workWords.Select(w=>w.Text));var wo=new OcrResult(workText,[],workWords,all.ImageWidth,all.ImageHeight,all.Duration);raw.Text=$"Location Raw OCR\r\n{locationText}\r\n\r\nWork Order Raw OCR\r\n{workText}";var parsedResult=RefinerySpatialParser.Parse(wo,locationText);parsed.Text=$"Location: {parsedResult.Location}\r\nScreen: {parsedResult.ScreenType}\r\n\r\n"+string.Join("\r\n",parsedResult.Rows.Select(r=>$"{r.NormalizedMaterialName,-12} {r.Quality,7} {r.YieldCscu,10} {r.Confidence:P0} {string.Join(",",r.Warnings)}"));if(parsedResult.Warnings.Count>0)parsed.AppendText("\r\n\r\nWarnings: "+string.Join(", ",parsedResult.Warnings));}catch(Exception ex){parsed.Text=$"OCR_FAILED\r\n{ex.Message}";}finally{if(File.Exists(fullPath))File.Delete(fullPath);}}
 static IReadOnlyList<OcrWord> FilterWords(OcrResult ocr,RegionOfInterest roi){var r=roi.ToPixels(ocr.ImageWidth,ocr.ImageHeight);var words=ocr.Words.Where(w=>RectangleF.Intersect(new RectangleF((float)w.X,(float)w.Y,(float)w.Width,(float)w.Height),r).Width>0).ToArray();return words;}
 async Task Scan(string imagePath){var sw=Stopwatch.StartNew();try{var text=await new WindowsOcrEngine().RecognizeAsync(imagePath);result=MiningParser.Parse(text);raw.Text=result.RawText;parsed.Text=string.Join(Environment.NewLine+Environment.NewLine,result.Rows.Select(r=>$"{r.NormalizedMaterialName} | Quality: {r.Quality?.ToString()??"?"} | Quantity: {r.Quantity?.ToString()??"?"} | Confidence: {r.Confidence:P0}\r\nWarnings: {string.Join(", ",r.Warnings)}"));if(string.IsNullOrWhiteSpace(text))parsed.AppendText("\r\n\r\nNO_TEXT_DETECTED");else if(result.Rows.Count==0)parsed.AppendText("\r\n\r\nNO_MINING_ROWS_DETECTED");parsed.AppendText($"\r\n\r\n{result.Rows.Count} rows detected; {result.Warnings.Count} warnings; {sw.ElapsedMilliseconds} ms");}catch(FileNotFoundException){parsed.Text="IMAGE_LOAD_FAILED";}catch(Exception ex){parsed.Text=$"OCR_FAILED\r\n{ex.Message}";}}
 void Export(){if(result==null)return;using var d=new SaveFileDialog{Filter="JSON|*.json",FileName="mining-ocr-result.json"};if(d.ShowDialog()==DialogResult.OK)File.WriteAllText(d.FileName,JsonSerializer.Serialize(new{schemaVersion=1,source="verselink-companion-phase0",rawText=result.RawText,rows=result.Rows},new JsonSerializerOptions{WriteIndented=true}));}
}
public sealed class RoiCanvas:Panel{
 Image? image;
 public Rectangle DragOverlay{get;set;} public Rectangle SavedLocationOverlay{get;set;} public Rectangle SavedWorkOrderOverlay{get;set;}
 public Color DragOverlayColor{get;set;}=Color.Lime;
 public RoiCanvas(){SetStyle(ControlStyles.UserPaint|ControlStyles.AllPaintingInWmPaint|ControlStyles.OptimizedDoubleBuffer,true);}
 public Image? Image{get=>image;set{image=value;ZoomFactor=1;Invalidate();}}
 public double ZoomFactor{get;private set;}=1;
 public Rectangle DisplayedImageRectangle{get{if(Image==null||ClientSize.Width==0||ClientSize.Height==0)return Rectangle.Empty;var s=Math.Min((double)ClientSize.Width/Image.Width,(double)ClientSize.Height/Image.Height)*ZoomFactor;var w=(int)(Image.Width*s);var h=(int)(Image.Height*s);return new Rectangle((ClientSize.Width-w)/2,(ClientSize.Height-h)/2,w,h);}}
 protected override void OnMouseWheel(MouseEventArgs e){ZoomFactor=Math.Clamp(ZoomFactor+(e.Delta>0?.1:-.1),.5,4);Invalidate();base.OnMouseWheel(e);}
 protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);if(Image!=null){var r=DisplayedImageRectangle;e.Graphics.DrawImage(Image,r);}using(var a=new Pen(Color.Lime,3))if(SavedLocationOverlay.Width>0)e.Graphics.DrawRectangle(a,SavedLocationOverlay);using(var b=new Pen(Color.Orange,3))if(SavedWorkOrderOverlay.Width>0)e.Graphics.DrawRectangle(b,SavedWorkOrderOverlay);if(DragOverlay.Width>0&&DragOverlay.Height>0)using(var pen=new Pen(DragOverlayColor,3)){pen.DashStyle=System.Drawing.Drawing2D.DashStyle.Dash;e.Graphics.DrawRectangle(pen,DragOverlay);}}
}
static class Program{[STAThread]static void Main(){ApplicationConfiguration.Initialize();Application.Run(new AutomaticForm());}}
