using System.Drawing;using System.Text.RegularExpressions;
namespace VerseLink.Companion;
public enum RegionType{Location,WorkOrder}
public readonly record struct RegionOfInterest(RegionType Type,double RelativeX,double RelativeY,double RelativeWidth,double RelativeHeight){public Rectangle ToPixels(int w,int h)=>new((int)(RelativeX*w),(int)(RelativeY*h),(int)(RelativeWidth*w),(int)(RelativeHeight*h));public static RegionOfInterest FromPixels(RegionType t,Rectangle r,int w,int h)=>new(t,(double)r.X/w,(double)r.Y/h,(double)r.Width/w,(double)r.Height/h);}
public sealed record OcrWord(string Text,double X,double Y,double Width,double Height);public sealed record OcrLine(string Text,IReadOnlyList<OcrWord> Words);public sealed record OcrResult(string RawText,IReadOnlyList<string> Lines,IReadOnlyList<OcrWord> Words,int ImageWidth,int ImageHeight,TimeSpan Duration);
public sealed record RefineryCompletedRow(string RawMaterialName,string NormalizedMaterialName,string RawQualityText,int? Quality,string RawYieldText,int? YieldCscu,double Confidence,IReadOnlyList<string> Warnings);public sealed record RefineryCompletedParseResult(string ScreenType,string Location,IReadOnlyList<RefineryCompletedRow> Rows,IReadOnlyList<string> Warnings){public string? PlayerName{get;init;}public string? LocationId{get;init;}public string? System{get;init;}public string RawLocation{get;init;}="";public LocationMatchType LocationMatchType{get;init;}=LocationMatchType.UNKNOWN;}
public static class ImageCropper{public static Bitmap CropImage(Bitmap i,RegionOfInterest r)=>i.Clone(r.ToPixels(i.Width,i.Height),i.PixelFormat);}
public static class RefinerySpatialParser{
 static string C(string s)=>Regex.Replace(s.ToUpperInvariant(),@"[^A-Z0-9]","");static int? N(string s){var x=s.Trim().Replace('O','0').Replace('I','1').Replace('L','1').Replace('S','5').Replace('B','8');return int.TryParse(x,out var n)?n:null;}static string Loc(string s){var v=C(s);var m=new Dictionary<string,string>{{"CHECKMATE","Checkmate"},{"EVERUSHARBOR","Everus Harbor"},{"LORVILLE","Lorville"},{"AREA18","Area 18"}};return m.FirstOrDefault(x=>v.Contains(x.Key,StringComparison.Ordinal)).Value??"UNKNOWN_LOCATION";}
 public static RefineryCompletedParseResult Parse(OcrResult o,string locationRaw="",string? systemHint=null){var w=o.Words;var headers=(from q in w where C(q.Text) is "QUALITY" or "QUALITV" from y in w where C(y.Text) is "YIELD" or "YIELO"&&y.X>q.X orderby Math.Abs(q.Y-y.Y)+Math.Abs(y.X-q.X)*.01 select(q,y)).FirstOrDefault();var qh=headers.q;var yh=headers.y;var rows=new List<RefineryCompletedRow>();if(qh!=null&&yh!=null){var mid=(qh.X+yh.X)/2;var t=Math.Max(8,w.Select(x=>x.Height).DefaultIfEmpty(12).Average());foreach(var g in w.Where(x=>x.Y>Math.Max(qh.Y,yh.Y)+t).GroupBy(x=>Math.Round(x.Y/t)).OrderBy(x=>x.Key)){var m=g.FirstOrDefault(x=>x.X<qh.X&&N(x.Text)==null);var q=g.Where(x=>x.X<mid&&N(x.Text)!=null).OrderBy(x=>Math.Abs(x.X-qh.X)).FirstOrDefault();var y=g.Where(x=>x.X>=mid&&N(x.Text)!=null).OrderBy(x=>Math.Abs(x.X-yh.X)).FirstOrDefault();if(m==null||q==null||y==null)continue;var ws=new List<string>();if(q.Text.Any(char.IsLetter)||y.Text.Any(char.IsLetter))ws.Add("OCR_NUMERIC_CORRECTION");rows.Add(new(m.Text,MaterialCatalog.Match(m.Text).Name,q.Text,N(q.Text),y.Text,N(y.Text),.9,ws));}}var match=RefineryLocationCatalog.Match(locationRaw,systemHint);var name=match.Name??(match.MatchType==LocationMatchType.AMBIGUOUS?"AMBIGUOUS_LOCATION":"UNKNOWN_LOCATION");return new(rows.Count>0?"REFINERY_COMPLETED_WORK_ORDER":"UNSUPPORTED_SCREEN_TYPE",name,rows,rows.Count==0?new[]{"NO_MINING_ROWS_DETECTED"}:Array.Empty<string>()){RawLocation=locationRaw,LocationId=match.LocationId,System=match.System,LocationMatchType=match.MatchType};}
}
